//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvaluationTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidate_Details()
        {
            this.Evaluation_Feedbacks = new HashSet<Evaluation_Feedbacks>();
        }
    
        public int Candidate_Id { get; set; }
        public string Candidate_Name { get; set; }
        public string Phone_No { get; set; }
        public string Email { get; set; }
        public string Resume { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evaluation_Feedbacks> Evaluation_Feedbacks { get; set; }
    }
}
