//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvaluationTracker.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CandidateEvaluationEntities1 : DbContext
    {
        public CandidateEvaluationEntities1()
            : base("name=CandidateEvaluationEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Candidate_Details> Candidate_Details { get; set; }
        public virtual DbSet<Evaluation_Feedbacks> Evaluation_Feedbacks { get; set; }
        public virtual DbSet<Interviewer_Details> Interviewer_Details { get; set; }
    }
}
